POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "title": "Voy a limpiar una pieza",
    "description": "tengo que pasar la aspiradora, trapear y hacer mi cama",
    "completed": true
}


###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "completed": false
}

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "title": "Hola mundo",
    "completed": false
}


###
DELETE http://localhost:3001/api/notes/6244dd06eb8beef01d42d64a


###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6245c58a7d1dfc01c4643ca9

###
PUT http://localhost:3001/api/notes/6245c58a7d1dfc01c4643ca9
Content-Type: application/json

{
    "description": "Solo hacer mi cama",
    "completed": false
}