POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "title": "Almorzar",
    "description": "Almuerzo congelado",
    "completed": false
}


###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "important": false
}

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "title": "Hola mundo",
    "completed": false
}


###
DELETE http://localhost:3001/api/notes/4


###
GET http://localhost:3001/api/notes